---
- name: Deploy Baseline Configuration to Network
  hosts: all
  connection: network_cli
  gather_facts: no

  tasks:
    - name: Configure MOTD Banner
      ios_banner:
        banner: motd
        text: Welcome. This banner is managed by Ansible.

    - name: Configure OSPF Routing
      ios_config:
        parents: router ospf 1
        lines:
          - network 10.0.0.0 0.0.0.255 area 0
          - network 192.168.0.0 0.0.0.255 area 0
